#FROM amazon/aws-sam-cli-build-image-python3.8 as aws-sam
FROM public.ecr.aws/sam/build-java21 as aws-sam

# https://docs.aws.amazon.com/sdkref/latest/guide/overview.html
# https://docs.aws.amazon.com/es_es/serverless-application-model/latest/developerguide/install-sam-cli.html
# https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
